/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(f){function m(a){a=a||{};a.transition&&(a[s+"transition"]=a.transition);a.transform&&(a[s+"transform"]=a.transform);return a}var q=document.createElement("div"),q=q.style,n,u,v="-webkit- -moz- -o- -ms- -khtml-".split(" "),t="Webkit Moz O ms Khtml".split(" "),s="";n=!1;for(var p=0;p<t.length;p++)if(q[t[p]+"Transition"]===""){n=t[p]+"Transition";s=v[p];break}n&&"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix&&navigator.userAgent.match(/Chrome/i);u=function(){var a=document.createElement("canvas");
return!(!a.getContext||!a.getContext("2d"))}();var q=null,h=function(){};h.prototype=f.extend(h.prototype,{name:"slideshow",options:{index:0,width:"auto",height:"auto",autoplay:!0,interval:5E3,navbar_items:4,caption_animation_duration:500,slices:20,duration:500,animated:"random",easing:"swing"},nav:null,navbar:null,captions:null,caption:null,kbi:0,initialize:function(a,c){var b=this,e=0,d=0;this.options=f.extend({},this.options,c);this.element=this.wrapper=a;this.ul=this.wrapper.find("ul.slides:first").css({width:"100%",
overflow:"hidden"});if(this.options.width=="auto")this.options.width=this.wrapper.width();this.wrapper.css({position:"relative",width:this.options.width});d=this.ul.width();this.ul.children().each(function(){e=Math.max(e,f(this).height())});if(this.options.height=="auto")this.options.height=e;this.slides=this.ul.css({position:"relative",height:this.options.height}).children().css({top:"0px",left:"0px",position:"absolute",width:d,height:this.options.height}).hide();this.index=this.slides[this.options.index]?
this.options.index:0;f(".next",this.wrapper).bind("click",function(){b.stop();b.nextSlide()});f(".prev",this.wrapper).bind("click",function(){b.stop();b.prevSlide()});f(this.slides.get(this.index)).show();if(this.wrapper.find(".nav:first").length){this.nav=this.wrapper.find(".nav:first");var l=this.nav.children();l.each(function(a){f(this).bind("click",function(){b.stop();b.slides[a]&&b.show(a)})});a.bind("slideshow-show",function(a,b,c){f(l.removeClass("active").get(c)).addClass("active")})}if(this.wrapper.find(".captions:first").length&&
this.wrapper.find(".caption:first").length)this.captions=this.wrapper.find(".captions:first").hide().children(),this.caption=this.wrapper.find(".caption:first").hide();this.nav&&f(this.nav.children().get(this.index)).addClass("active");this.navbar&&f(this.navbar.children().get(this.index)).addClass("active");this.showCaption(this.index);this.timer=null;this.hover=!1;this.wrapper.hover(function(){b.hover=!0},function(){b.hover=!1});this.options.autoplay&&this.start();this.options.animated=="kenburns"&&
this.show(this.index,!0);"ontouchend"in document&&(a.bind("touchstart",function(b){function c(a){if(d){var b=a.originalEvent.touches?a.originalEvent.touches[0]:a;k={time:(new Date).getTime(),coords:[b.pageX,b.pageY]};Math.abs(d.coords[0]-k.coords[0])>10&&a.preventDefault()}}var e=b.originalEvent.touches?b.originalEvent.touches[0]:b,d={time:(new Date).getTime(),coords:[e.pageX,e.pageY],origin:f(b.target)},k;a.bind("touchmove",c).one("touchend",function(){a.unbind("touchmove",c);d&&k&&k.time-d.time<
1E3&&Math.abs(d.coords[0]-k.coords[0])>30&&Math.abs(d.coords[1]-k.coords[1])<75&&d.origin.trigger("swipe").trigger(d.coords[0]>k.coords[0]?"swipeleft":"swiperight");d=k=void 0})}),this.wrapper.bind("swipeleft",function(){b.stop();b.nextSlide()}).bind("swiperight",function(){b.stop();b.prevSlide()}))},nextSlide:function(){this.show(this.slides[this.index+1]?this.index+1:0)},prevSlide:function(){this.show(this.index-1>-1?this.index-1:this.slides.length-1)},show:function(a,c){if(!(this.index==a&&!c||
this.fx&&this.options.animated!="kenburns"))this.current=f(this.slides.get(this.index)),this.next=f(this.slides.get(a)),this.animated=this.options.animated,this.duration=this.options.duration,this.easing=this.options.easing,this.dir=a>this.index?"right":"left",this.init=c,this.showCaption(a),this.element.trigger("slideshow-show",[this.index,a]),this.index=a,this[this.animated]?(this.fx=!0,this[this.animated]()):(this.current.hide(),this.next.show())},showCaption:function(a){if(this.caption&&this.captions[a]){var c=
f(this.captions.get(a)).html();this.caption.is(":animated")&&this.caption.stop();if(f.trim(c)=="")this.caption.is(":visible")&&this.caption.fadeOut(this.options.caption_animation_duration);else if(this.caption.is(":visible")){var b=this;this.caption.fadeOut(this.options.caption_animation_duration,function(){f(this).html(c).delay(200).css("opacity","").fadeIn(b.options.caption_animation_duration)})}else this.caption.html(c).fadeIn(this.options.caption_animation_duration)}},start:function(){if(!this.timer){var a=
this;this.timer=setInterval(function(){(a.options.animated=="kenburns"||!a.hover&&!a.fx)&&a.nextSlide()},this.options.interval)}},stop:function(){if(this.timer){clearInterval(this.timer);this.tmptimer&&clearTimeout(this.tmptimer);var a=this;this.tmptimer=setTimeout(function(){a.start();this.tmptimer=!1},3E4);this.timer=!1}},bindTransitionEnd:function(a){var c=this;f(a).bind("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){c.fx=null;c.next.css({"z-index":"2",left:0,top:0}).show();
c.current.hide();c.slicer.remove()})},randomSimple:function(){var a="top,bottom,left,right,fade,scrollLeft,scrollRight,scroll".split(",");this.animated=a[Math.floor(Math.random()*a.length)];this[this.animated]()},randomFx:function(){var a="sliceUp,sliceDown,sliceUpDown,fold,puzzle,boxes,boxesRtl".split(",");this.animated=a[Math.floor(Math.random()*a.length)];this[this.animated]()},top:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:0,top:this.wrapper.height()*
(this.animated=="bottom"?2:-1)}).animate({top:0},{duration:a.duration,easing:a.easing,complete:function(){a.fx=null;a.current.hide()}})},bottom:function(){this.top.apply(this)},left:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*(this.animated=="right"?2:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()}})},right:function(){this.left()},fade:function(){var a=this;
this.next.css({top:0,left:0,"z-index":1}).fadeIn(a.duration);this.current.css({"z-index":2}).fadeOut(this.duration,function(){a.fx=null;a.current.hide().css({opacity:1})})},scrollLeft:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*(this.animated=="scrollRight"?1:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()},step:function(c,b){a.current.css("left",(Math.abs(b.start)-
Math.abs(c))*(a.animated=="scrollRight"?-1:1))}})},scrollRight:function(){this.scrollLeft(this)},scroll:function(){var a=this;this.current.css({"z-index":1});this.next.css({"z-index":2,display:"block",left:this.current.width()*(this.dir=="right"?1:-1)}).animate({left:0},{duration:a.duration,easing:this.easing,complete:function(){a.fx=null;a.current.hide()},step:function(c,b){a.current.css("left",(Math.abs(b.start)-Math.abs(c))*(a.dir=="right"?-1:1))}})},slice:function(){var a=this,c=this.next.find("img:first"),
b=this.animated=="sliceUp"?"bottom":"top";if(c.length){var e=this.current.find("img:first").position();r(this,e.top,e.left);for(var e=Math.round(this.slicer.width()/this.options.slices),d=0;d<this.options.slices;d++){var l=d==this.options.slices-1?this.slicer.width()-e*d:e;this.animated=="sliceUpDown"&&(b=(d%2+2)%2==0?"top":"bottom");this.slicer.append(f("<div />").css(b,0).css(m({position:"absolute",left:e*d+"px",width:l+"px",height:0,background:"url("+c.attr("src")+") no-repeat -"+(e+d*e-e)+"px "+
b,opacity:0,transition:"all "+a.duration+"ms ease-in "+d*60+"ms"})))}this.slices=this.slicer.children();this.bindTransitionEnd.apply(this,[this.slices.get(this.slices.length-1)]);this.current.css({"z-index":1});this.slicer.show();var i=this.wrapper.height();if(n)this.slices.css(m({height:i,opacity:1}));else{var g=0;this.slices.each(function(b){var c=f(this);setTimeout(function(){c.animate({height:i,opacity:1},a.duration,function(){b==a.slices.length-1&&f(this).trigger("transitionend")})},g);g+=60})}}else this.next.css({"z-index":"2",
left:0,top:0}).show(),this.current.hide(),this.fx=null},sliceUp:function(){this.slice.apply(this)},sliceDown:function(){this.slice.apply(this)},sliceUpDown:function(){this.slice.apply(this)},fold:function(){var a=this,c=this.next.find("img:first");if(c.length){var b=this.current.find("img:first").position();r(this,b.top,b.left);for(var e=Math.round(this.slicer.width()/this.options.slices)+2,b=0;b<this.options.slices+1;b++){var d=b==a.options.slices?a.slicer.width()-e*b:e;this.slicer.append(f("<div />").css(m({position:"absolute",
left:e*b+"px",width:d,top:"0px",height:a.options.height,background:"url("+c.attr("src")+") no-repeat -"+(e+b*e-e)+"px 0%",opacity:0,transform:"scalex(0.0001)",transition:"all "+a.duration+"ms ease-in "+(100+b*60)+"ms"})))}this.slices=this.slicer.children();this.bindTransitionEnd.apply(this,[this.slices.get(this.slices.length-1)]);this.current.css({"z-index":1});this.slicer.show();if(n)this.slices.css(m({opacity:1,transform:"scalex(1)"}));else{var l=0;this.slices.width(0).each(function(b){var c=b==
a.options.slices-1?a.slicer.width()-e*b:e,d=f(this);setTimeout(function(){d.animate({opacity:1,width:c},a.duration,function(){b==a.slices.length-1&&f(this).trigger("transitionend")})},l+100);l+=50})}}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},puzzle:function(){var a=this,c=Math.round(this.options.slices/2),b=Math.round(this.wrapper.width()/c),e=Math.round(this.wrapper.height()/b),d=Math.round(this.wrapper.height()/e)+1,l=this.next.find("img:first");if(l.length){var i=
this.current.find("img:first").position();r(this,i.top,i.left);for(var i=this.wrapper.width(),g=0;g<e;g++)for(var j=0;j<c;j++){var h=f("<div />").css(m({position:"absolute",left:b*j+"px",width:j==c-1?i-b*j+"px":b+"px",top:d*g+"px",height:d+"px",background:"url("+l.attr("src")+") no-repeat -"+(b+j*b-b)+"px -"+(d+g*d-d)+"px",opacity:0,transition:"all "+a.duration+"ms ease-in 0ms"}));p+=1;this.slicer.append(h)}this.slices=w(this.slicer.children());this.bindTransitionEnd.apply(this,[this.slices.get(this.slices.length-
1)]);this.current.css({"z-index":1});this.slicer.show();this.slices.each(function(b){var c=f(this);setTimeout(function(){n?c.css(m({opacity:1})):c.animate({opacity:1},a.duration,function(){b==a.slices.length-1&&f(this).trigger("transitionend")})},100+b*50)})}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},boxes:function(){var a=this,c=Math.round(this.options.slices/2),b=Math.round(this.wrapper.width()/c),e=Math.round(this.wrapper.height()/b),d=Math.round(this.wrapper.height()/
e)+1,l=0,i=this.next.find("img:first");if(i.length){var g=this.current.find("img:first").position();r(this,g.top,g.left);for(g=0;g<e;g++)for(var j=0;j<c;j++)this.slicer.append(f("<div />").css(m({position:"absolute",left:b*j+"px",width:0,top:d*g+"px",height:0,background:"url("+i.attr("src")+") no-repeat -"+(b+j*b-b)+"px -"+(d+g*d-d)+"px",opacity:0,transition:"all "+(100+a.duration)+"ms ease-in 0ms"})).data("base",{width:j==c-1?this.wrapper.width()-b*j:b,height:d}));this.slices=this.slicer.children();
this.current.css({"z-index":1});this.slicer.show();var h=0,k=0,o=[];o[h]=[];b=this.animated=="boxesRtl"?this.slices._reverse():this.slices;this.bindTransitionEnd.apply(this,[b.get(b.length-1)]);b.each(function(){o[h][k]=f(this);k++;k==c&&(h++,k=0,o[h]=[])});for(j=d=0;j<c*e;j++){i=j;for(g=0;g<e;g++)i>=0&&i<c&&(function(b,c,e,d){var g=o[b][c];setTimeout(function(){n?g.css({opacity:"1",width:g.data("base").width,height:g.data("base").height}):g.animate({opacity:"1",width:g.data("base").width,height:g.data("base").height},
a.duration,function(){d==a.slices.length-1&&f(this).trigger("transitionend")})},100+e)}(g,i,l,d,b.length),d++),i--;l+=100}}else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null},boxesRtl:function(){this.boxes.apply(this)},kenburns:function(){var a=this,c=this.next.find("img:first");if(c.length)if(u){c.stop(!1,!0).data("width")&&c.css({width:c.data("width"),height:c.data("height")});this.slides.not(this.current).not(this.next).hide();this.current.css({"z-index":1});
this.next.css({"z-index":2,visibility:"hidden",opacity:1}).show();this.next.find("canvas").remove();c.position();var b=c.width(),e=c.height(),d=[{start:["t-r",1],stop:["b-l",1.2]},{start:["c-r",1.2],stop:["c-l",1]},{start:["b-l",1],stop:["t-r",1.2]},{start:["c-c",1.2],stop:["c-c",1]},{start:["t-c",1],stop:["b-c",1.2]},{start:["b-r",1],stop:["t-l",1.2]},{start:["c-l",1],stop:["c-r",1.2]},{start:["t-l",1.2],stop:["b-r",1]},{start:["c-c",1],stop:["c-c",1.2]},{start:["b-c",1.2],stop:["t-c",1]}],h=d[this.kbi?
this.kbi:0],i=f("<canvas></canvas>").attr({width:b,height:e}).css({width:b,height:e,opacity:0}),g=function(a,c){var c=c||1,d={top:0,left:0,width:b*c,height:e*c};switch(a){case "t-l":d.top=d.left=0;break;case "t-c":d.top=0;d.left=-1*((d.width-b)/2);break;case "t-r":d.top=0;d.left=-1*(d.width-b);break;case "c-l":d.top=-1*((d.height-e)/2);d.left=0;break;case "c-c":d.top=-1*((d.height-e)/2);d.left=-1*((d.width-b)/2);break;case "c-r":d.top=-1*((d.height-e)/2);d.left=-1*(d.width-b);break;case "b-l":d.top=
-1*(d.height-e);d.left=0;break;case "b-c":d.top=-1*(d.height-e);d.left=-1*((d.width-b)/2);break;case "b-r":d.top=-1*(d.height-e),d.left=-1*(d.width-b)}return d};c.css({position:"absolute","image-rendering":"optimizeQuality","-ms-interpolation-mode":"bicubic"}).after(i).hide();var j=i.get(0).getContext("2d");this.next.css({visibility:"visible"});i.animate({opacity:1},a.duration/5);var m=!1,k=!1,o=!1,n=!1;c.css(g.apply(this,h.start)).animate(g.apply(this,h.stop),{step:function(a,b){m!==!1&&k!==!1&&
o!==!1&&n!==!1&&(j.drawImage(c.get(0),m,k,o,n),n=o=k=m=!1);b.prop=="width"&&(o=a);b.prop=="height"&&(n=a);b.prop=="left"&&(m=a);b.prop=="top"&&(k=a)},complete:function(){i.remove();f(this).data({width:b,height:e}).show();a.fx=null},easing:a.easing,duration:a.duration});a.kbi=d[a.kbi+1]?a.kbi+1:0}else this.fade(this);else this.next.css({"z-index":"2",left:0,top:0}).show(),this.current.hide(),this.fx=null}});f.fn._reverse=[].reverse;var w=function(a){for(var c,b,e=a.length;e;c=parseInt(Math.random()*
e),b=a[--e],a[e]=a[c],a[c]=b);return a},r=function(a,c,b){c=c||0;b=b||0;a.slicer=f("<li />").addClass("slices").css({top:c,left:b,position:"absolute",width:a.wrapper.width(),height:a.ul.height(),"z-index":3}).hide().appendTo(a.ul)};f.fn[h.prototype.name]=function(){var a=arguments,c=a[0]?a[0]:null;return this.each(function(){var b=f(this);if(h.prototype[c]&&b.data(h.prototype.name)&&c!="initialize")b.data(h.prototype.name)[c].apply(b.data(h.prototype.name),Array.prototype.slice.call(a,1));else if(!c||
f.isPlainObject(c)){var e=new h;h.prototype.initialize&&e.initialize.apply(e,f.merge([b],a));b.data(h.prototype.name,e)}else f.error("Method "+c+" does not exist on jQuery."+h.name)})}})(jQuery);
