/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(g){function n(e){e=e||{};e.transition&&(e[q+"transition"]=e.transition);e.transform&&(e[q+"transform"]=e.transform);return e}var w=document.createElement("div"),w=w.style,p,m="-webkit- -moz- -o- -ms- -khtml-".split(" "),r="Webkit Moz O ms Khtml".split(" "),q="";p=false;for(var k=0;k<r.length;k++)if(w[r[k]+"Transition"]===""){p=r[k]+"Transition";q=m[k];break}p&&"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix&&navigator.userAgent.match(/Chrome/i);var w=null,x=[],i=function(){},z={width:"auto",
height:"auto",index:0,autoplay:false,effect:"slide",interval:5E3,easing:"easeOutCirc",duration:300};i.prototype=g.extend(i.prototype,{name:"slideset",initialize:function(e){this.options=g.extend({},z,e);var b=this,h=this.element;this.sets=h.find("ul.set");this.navitems=h.find("ul.nav").children();this.current=this.sets[this.options.index]?this.options.index:0;this.busy=false;this.timer=null;this.hover=false;this.gwidth=this.options.width=="auto"?h.width():this.options.width;this.gheight=this.options.height==
"auto"?this.sets.eq(0).outerHeight(true):this.options.height;h.css({width:b.gwidth});this.sets.css({height:b.gheight});this.sets.each(function(a){b.sets.eq(a).children().each(function(){var a=g(this),b=a.position();a.data("left",b.left)});b.sets.eq(a).children().each(function(){var a=g(this);a.css("position","absolute").css("left",a.data("left"))});b.sets.eq(a).hide()});this.navitems.each(function(a){g(this).bind("click",function(){b.stop().show(a)})});h.find(".next, .prev").bind("click",function(){b.stop()[g(this).hasClass("next")?
"next":"previous"]()});"ontouchend"in document&&(h.bind("touchstart",function(a){function d(a){if(c){var d=a.originalEvent.touches?a.originalEvent.touches[0]:a;e={time:(new Date).getTime(),coords:[d.pageX,d.pageY]};Math.abs(c.coords[0]-e.coords[0])>10&&a.preventDefault()}}var b=a.originalEvent.touches?a.originalEvent.touches[0]:a,c={time:(new Date).getTime(),coords:[b.pageX,b.pageY],origin:g(a.target)},e;h.bind("touchmove",d).one("touchend",function(){h.unbind("touchmove",d);c&&e&&e.time-c.time<1E3&&
Math.abs(c.coords[0]-e.coords[0])>30&&Math.abs(c.coords[1]-e.coords[1])<75&&c.origin.trigger("swipe").trigger(c.coords[0]>e.coords[0]?"swipeleft":"swiperight");c=e=void 0})}),h.bind("swipeleft",function(){b.next()}).bind("swiperight",function(){b.previous()}));this.sets.eq(this.current).show();jQuery.support.opacity&&this.sets.eq(this.current).css("transform","scale(0.1)").animate({transform:"scale(1.0)"},{easing:"easeOutCirc",duration:500});this.navitems.eq(this.current).addClass("active");h.hover(function(){b.hover=
true},function(){b.hover=false});this.options.autoplay&&this.start()},next:function(){this.show(this.sets[this.current+1]?this.current+1:0)},previous:function(){this.show(this.current-1>-1?this.current-1:this.sets.length-1)},start:function(){if(!this.timer){var e=this;this.timer=setInterval(function(){!e.hover&&!e.busy&&e.next()},this.options.interval);return this}},stop:function(){if(this.timer){clearInterval(this.timer);this.tmptimer&&clearTimeout(this.tmptimer);var e=this;this.tmptimer=setTimeout(function(){e.start();
this.tmptimer=false},3E4);this.timer=false}return this},show:function(e){this.current==e||this.busy||(this.element.trigger("slideset-show",[this.current,e]),this[this[this.options.effect]?this.options.effect:"slide"](e),this.navitems.removeClass("active").eq(e).addClass("active"))},slide:function(e){var b=e>this.current?"left":"right",h=this.sets.eq(e),a=this;this.busy=true;this.sets.eq(this.current).animate({"margin-left":(b=="left"?-1:1)*2*this.gwidth},{complete:function(){h.css("margin-left",0).children().hide().css({left:(b==
"left"?1:-1)*2*a.gwidth});h.show();a.sets.eq(a.current).hide();var d=h.children(),f=0;d.each(function(c){b=="right"&&(c=d.length-1-c);(function(c,e){setTimeout(function(){d.eq(c).show().animate({left:d.eq(c).data("left")},{complete:function(){if(b=="left"&&c==d.length-1||b=="right"&&c==0)a.busy=false,a.current=e},duration:a.options.duration,easing:a.options.easing})},100*f)})(c,e);f+=1})}})},zoom:function(e){var b=this.sets.eq(e),h=0,a=this.sets.eq(this.current).children(),d=this;this.busy=true;this.sets.eq(this.current).children().animate(jQuery.support.opacity?
{transform:"scale(0)",opacity:0}:{opacity:0},{complete:function(){h+=1;if(!(h!=-1&&h<a.length-1)){h=-1;var f=b.children().css(jQuery.support.opacity?{transform:"scale(0)",opacity:0}:{opacity:0}),c=0;d.sets.eq(d.current).hide();b.css("margin-left","").show();f.each(function(a){f.eq(a).css({left:f.eq(a).data("left")}).show();(function(a,b){setTimeout(function(){f.eq(a).show().animate(jQuery.support.opacity?{transform:"scale(1)",opacity:1}:{opacity:1},{complete:function(){if(a==f.length-1)d.busy=false,
d.current=b},duration:d.options.duration,easing:d.options.easing})},Math.round(d.options.duration/3)*c)})(a,e);c+=1})}},easing:"swing",duration:Math.round(d.options.duration/2)})},deck:function(e){if(!jQuery.support.opacity)return this.zoom(e);var b=e>this.current?"left":"right",h=this.sets.eq(e),a=this.sets.eq(this.current).children(),d=this.sets.eq(e).children();a[e>this.current?"first":"last"]();d[e>this.current?"last":"first"]();var f=this;b=="right"&&a._reverse();b=="right"&&d._reverse();this.busy=
true;a.each(function(b){var v=g(this);(function(b,c){setTimeout(function(){c.animate({transform:"scale(0)",opacity:0},{complete:function(){c.hide();b==a.length-1&&(f.sets.eq(f.current).hide(),d.css({transform:"scale(0)",opacity:0}),h.css("margin-left","").show(),d.each(function(b){var c=g(this);(function(b,c){setTimeout(function(){c.animate({transform:"scale(1)",opacity:1},{complete:function(){if(b==d.length-1)a.show().each(function(b){a.eq(b).css({transform:"scale(1)",opacity:1,left:a.eq(b).data("left")})}),
f.busy=false,f.current=e},duration:f.options.duration,easing:f.options.easing})},Math.round(f.options.duration/3)*b)})(b,c)}))},duration:f.options.duration,easing:f.options.easing})},Math.round(f.options.duration/3)*b)})(b,v)})},drops:function(e){if(!jQuery.support.opacity)return this.zoom(e);var b=e>this.current?"left":"right",h=this.sets.eq(e),a=this.sets.eq(this.current).children().css(n({transition:""})).css(n({transform:"rotate(0deg)",top:0,opacity:1})),d=this.sets.eq(e).children().css(n({transition:""}));
a[e>this.current?"first":"last"]();d[e>this.current?"last":"first"]();var f=this;b=="right"&&a._reverse();b=="right"&&d._reverse();this.busy=true;a.each(function(b){var v=g(this);(function(b,c){setTimeout(function(){if(p){c.css(n({transition:"all "+f.options.duration+"ms ease-out"}));if(b==a.length-1)c.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){f.sets.eq(f.current).hide();d.css(n({top:f.gheight,opacity:0,transform:"rotate(15deg)"}));h.css("margin-left","").show();
d.each(function(a){var b=g(this);(function(a,b){setTimeout(function(){b.css(n({transition:"all "+f.options.duration+"ms ease-in"}));if(a==d.length-1)b.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){f.busy=false;f.current=e});b.css(n({opacity:1,top:0,transform:"rotate(0deg)"}))},Math.round(f.options.duration/3)*a)})(a,b)})});c.css(n({opacity:0,top:f.gheight,transform:"rotate(15deg)"}))}else c.animate({opacity:0,top:f.gheight},{complete:function(){c.hide();b==a.length-
1&&(f.sets.eq(f.current).hide(),d.css({top:f.gheight,opacity:0}),h.css("margin-left","").show(),d.each(function(b){var c=g(this);(function(b,c){setTimeout(function(){c.animate({opacity:1,top:0},{complete:function(){if(b==d.length-1)a.show().each(function(b){a.eq(b).css({opacity:1,top:0})}),f.busy=false,f.current=e},duration:f.options.duration,easing:f.options.easing})},Math.round(f.options.duration/3)*b)})(b,c)}))},duration:f.options.duration,easing:f.options.easing})},20+Math.round(f.options.duration/
3)*b)})(b,v)})}});if(!g.fn._reverse)g.fn._reverse=[].reverse;g.fn[i.prototype.name]=function(){var e=arguments,b=e[0]?e[0]:null;return this.each(function(){var h=g(this);if(i.prototype[b]&&h.data(i.prototype.name)&&b!="initialize")h.data(i.prototype.name)[b].apply(h.data(i.prototype.name),Array.prototype.slice.call(e,1));else if(!b||g.isPlainObject(b)){var a=new i;a.element=h;x.push(a);i.prototype.initialize&&a.initialize.apply(a,e);h.data(i.prototype.name,a)}else g.error("Method "+b+" does not exist on jQuery."+
i.prototype.name)})}})(jQuery);
(function(g){function n(b){for(var b=b.split(")"),e=g.trim,a=b.length-1,d,f,c,v=1,i=0,k=0,n=1,o,s,l,m=0,u=0;a--;){d=b[a].split("(");f=e(d[0]);c=d[1];o=d=s=l=0;switch(f){case "translateX":m+=parseInt(c,10);continue;case "translateY":u+=parseInt(c,10);continue;case "translate":c=c.split(",");m+=parseInt(c[0],10);u+=parseInt(c[1]||0,10);continue;case "rotate":c=p(c);o=Math.cos(c);d=Math.sin(c);s=-Math.sin(c);l=Math.cos(c);break;case "scaleX":o=c;l=1;break;case "scaleY":o=1;l=c;break;case "scale":c=c.split(",");
o=c[0];l=c.length>1?c[1]:c[0];break;case "skewX":o=l=1;s=Math.tan(p(c));break;case "skewY":o=l=1;d=Math.tan(p(c));break;case "skew":o=l=1;c=c.split(",");s=Math.tan(p(c[0]));d=Math.tan(p(c[1]||0));break;case "matrix":c=c.split(","),o=+c[0],d=+c[1],s=+c[2],l=+c[3],m+=parseInt(c[4],10),u+=parseInt(c[5],10)}f=v*o+i*s;i=v*d+i*l;o=k*o+n*s;n=k*d+n*l;v=f;k=o}return[v,i,k,n,m,u]}function w(b){var e,a,d,f=b[0],c=b[1],g=b[2],i=b[3];f*i-c*g?(e=Math.sqrt(f*f+c*c),f/=e,c/=e,d=f*g+c*i,g-=f*d,i-=c*d,a=Math.sqrt(g*
g+i*i),g/=a,i/=a,d/=a,f*i<c*g&&(f=-f,c=-c,d=-d,e=-e)):rotate=e=a=d=0;return{translate:[+b[4],+b[5]],rotate:Math.atan2(c,f),scale:[e,a],skew:[d,0]}}function p(b){return~b.indexOf("deg")?parseInt(b,10)*(Math.PI*2/360):~b.indexOf("grad")?parseInt(b,10)*(Math.PI/200):parseFloat(b)}for(var m=document.createElement("div"),m=m.style,r=["OTransform","msTransform","WebkitTransform","MozTransform","transform"],q=r.length,k,x,i,z,e=/Matrix([^)]*)/;q--;)r[q]in m&&(g.support.transform=k=r[q]);if(!k)g.support.matrixFilter=
x=m.filter==="";m=m=null;g.cssNumber.transform=true;k&&k!="transform"?(g.cssProps.transform=k,k=="MozTransform"?i={get:function(b,e){return e?g.css(b,k).split("px").join(""):b.style[k]},set:function(b,e){b.style[k]=/matrix[^)p]*\)/.test(e)?e.replace(/matrix((?:[^,]*,){4})([^,]*),([^)]*)/,"matrix$1$2px,$3px"):e}}:/^1\.[0-5](?:\.|$)/.test(g.fn.jquery)&&(i={get:function(b,e){return e?g.css(b,k.replace(/^ms/,"Ms")):b.style[k]}})):x&&(i={get:function(b,h){var a=h&&b.currentStyle?b.currentStyle:b.style,
d;a&&e.test(a.filter)?(d=RegExp.$1.split(","),d=[d[0].split("=")[1],d[2].split("=")[1],d[1].split("=")[1],d[3].split("=")[1]]):d=[1,0,0,1];d[4]=a?a.left:0;d[5]=a?a.top:0;return"matrix("+d+")"},set:function(b,h,a){var d=b.style,f,c,i;if(!a)d.zoom=1;h=n(h);if(!a||a.M)if(c=["Matrix(M11="+h[0],"M12="+h[2],"M21="+h[1],"M22="+h[3],"SizingMethod='auto expand'"].join(),i=(f=b.currentStyle)&&f.filter||d.filter||"",d.filter=e.test(i)?i.replace(e,c):i+" progid:DXImageTransform.Microsoft."+c+")",centerOrigin=
g.transform.centerOrigin)d[centerOrigin=="margin"?"marginLeft":"left"]=-(b.offsetWidth/2)+b.clientWidth/2+"px",d[centerOrigin=="margin"?"marginTop":"top"]=-(b.offsetHeight/2)+b.clientHeight/2+"px";if(!a||a.T)d.left=h[4]+"px",d.top=h[5]+"px"}});i&&(g.cssHooks.transform=i);z=i&&i.get||g.css;g.fx.step.transform=function(b){var e=b.elem,a=b.start,d=b.end,f,c=b.pos,m,q,r,A,o=false,s=false,l;m=q=r=A="";if(!a||typeof a==="string"){a||(a=z(e,k));if(x)e.style.zoom=1;f=d.split(a);if(f.length==2)d=f.join(""),
b.origin=a,a="none";a=="none"?a={translate:[0,0],rotate:0,scale:[1,1],skew:[0,0]}:(a=/\(([^,]*),([^,]*),([^,]*),([^,]*),([^,p]*)(?:px)?,([^)p]*)(?:px)?/.exec(a),a=w([a[1],a[2],a[3],a[4],a[5],a[6]]));b.start=a;if(~d.indexOf("matrix"))d=w(n(d));else{d=d.split(")");f=[0,0];for(var B=0,u=[1,1],y=[0,0],C=d.length-1,D=g.trim,j,t;C--;)j=d[C].split("("),t=D(j[0]),j=j[1],t=="translateX"?f[0]+=parseInt(j,10):t=="translateY"?f[1]+=parseInt(j,10):t=="translate"?(j=j.split(","),f[0]+=parseInt(j[0],10),f[1]+=parseInt(j[1]||
0,10)):t=="rotate"?B+=p(j):t=="scaleX"?u[0]*=j:t=="scaleY"?u[1]*=j:t=="scale"?(j=j.split(","),u[0]*=j[0],u[1]*=j.length>1?j[1]:j[0]):t=="skewX"?y[0]+=p(j):t=="skewY"?y[1]+=p(j):t=="skew"&&(j=j.split(","),y[0]+=p(j[0]),y[1]+=p(j[1]||"0"));d={translate:f,rotate:B,scale:u,skew:y}}b.end=d;for(l in a)(l=="rotate"?a[l]==d[l]:a[l][0]==d[l][0]&&a[l][1]==d[l][1])&&delete a[l]}a.translate&&(m=" translate("+(a.translate[0]+(d.translate[0]-a.translate[0])*c+0.5|0)+"px,"+(a.translate[1]+(d.translate[1]-a.translate[1])*
c+0.5|0)+"px)",o=true);a.rotate!=void 0&&(q=" rotate("+(a.rotate+(d.rotate-a.rotate)*c)+"rad)",s=true);a.scale&&(r=" scale("+(a.scale[0]+(d.scale[0]-a.scale[0])*c)+","+(a.scale[1]+(d.scale[1]-a.scale[1])*c)+")",s=true);a.skew&&(A=" skew("+(a.skew[0]+(d.skew[0]-a.skew[0])*c)+"rad,"+(a.skew[1]+(d.skew[1]-a.skew[1])*c)+"rad)",s=true);b=b.origin?b.origin+m+A+r+q:m+q+r+A;i&&i.set?i.set(e,b,{M:s,T:o}):e.style[k]=b};g.transform={centerOrigin:"margin"}})(jQuery);
