/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(g){function o(e){e=e||{};e.transition&&(e[r+"transition"]=e.transition);e.transform&&(e[r+"transform"]=e.transform);return e}var w=document.createElement("div"),w=w.style,q,n="-webkit- -moz- -o- -ms- -khtml-".split(" "),s="Webkit Moz O ms Khtml".split(" "),r="";q=!1;for(var l=0;l<s.length;l++)if(w[s[l]+"Transition"]===""){q=s[l]+"Transition";r=n[l];break}q&&"WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix&&navigator.userAgent.match(/Chrome/i);var w=null,x=[],j=function(){},z={width:"auto",
height:"auto",index:0,autoplay:!1,effect:"slide",interval:5E3,easing:"easeOutCirc",duration:300};j.prototype=g.extend(j.prototype,{name:"slideset",initialize:function(e){this.options=g.extend({},z,e);var b=this,h=this.element;this.sets=h.find("ul.set");this.navitems=h.find("ul.nav").children();this.current=this.sets[this.options.index]?this.options.index:0;this.busy=!1;this.timer=null;this.hover=!1;this.gwidth=this.options.width=="auto"?h.width():this.options.width;this.gheight=this.options.height==
"auto"?this.sets.eq(0).outerHeight(!0):this.options.height;h.css({width:b.gwidth});this.sets.css({height:b.gheight});this.sets.each(function(a){b.sets.eq(a).children().each(function(){var a=g(this),b=a.position();a.data("left",b.left)});b.sets.eq(a).children().each(function(){var a=g(this);a.css("position","absolute").css("left",a.data("left"))});b.sets.eq(a).hide()});this.navitems.each(function(a){g(this).bind("click",function(){b.stop().show(a)})});h.find(".next, .prev").bind("click",function(){b.stop()[g(this).hasClass("next")?
"next":"previous"]()});"ontouchend"in document&&(h.bind("touchstart",function(a){function d(a){if(c){var d=a.originalEvent.touches?a.originalEvent.touches[0]:a;e={time:(new Date).getTime(),coords:[d.pageX,d.pageY]};Math.abs(c.coords[0]-e.coords[0])>10&&a.preventDefault()}}var b=a.originalEvent.touches?a.originalEvent.touches[0]:a,c={time:(new Date).getTime(),coords:[b.pageX,b.pageY],origin:g(a.target)},e;h.bind("touchmove",d).one("touchend",function(){h.unbind("touchmove",d);c&&e&&e.time-c.time<1E3&&
Math.abs(c.coords[0]-e.coords[0])>30&&Math.abs(c.coords[1]-e.coords[1])<75&&c.origin.trigger("swipe").trigger(c.coords[0]>e.coords[0]?"swipeleft":"swiperight");c=e=void 0})}),h.bind("swipeleft",function(){b.next()}).bind("swiperight",function(){b.previous()}));this.sets.eq(this.current).show();jQuery.support.opacity&&this.sets.eq(this.current).css("transform","scale(0.1)").animate({transform:"scale(1.0)"},{easing:"easeOutCirc",duration:500});this.navitems.eq(this.current).addClass("active");h.hover(function(){b.hover=
!0},function(){b.hover=!1});this.options.autoplay&&this.start()},next:function(){this.show(this.sets[this.current+1]?this.current+1:0)},previous:function(){this.show(this.current-1>-1?this.current-1:this.sets.length-1)},start:function(){if(!this.timer){var e=this;this.timer=setInterval(function(){!e.hover&&!e.busy&&e.next()},this.options.interval);return this}},stop:function(){if(this.timer){clearInterval(this.timer);this.tmptimer&&clearTimeout(this.tmptimer);var e=this;this.tmptimer=setTimeout(function(){e.start();
this.tmptimer=!1},3E4);this.timer=!1}return this},show:function(e){this.current==e||this.busy||(this.element.trigger("slideset-show",[this.current,e]),this[this[this.options.effect]?this.options.effect:"slide"](e),this.navitems.removeClass("active").eq(e).addClass("active"))},slide:function(e){var b=e>this.current?"left":"right",h=this.sets.eq(e),a=this;this.busy=!0;this.sets.eq(this.current).animate({"margin-left":(b=="left"?-1:1)*2*this.gwidth},{complete:function(){h.css("margin-left",0).children().hide().css({left:(b==
"left"?1:-1)*2*a.gwidth});h.show();a.sets.eq(a.current).hide();var d=h.children(),f=0;d.each(function(c){b=="right"&&(c=d.length-1-c);(function(c,e){setTimeout(function(){d.eq(c).show().animate({left:d.eq(c).data("left")},{complete:function(){if(b=="left"&&c==d.length-1||b=="right"&&c==0)a.busy=!1,a.current=e},duration:a.options.duration,easing:a.options.easing})},100*f)})(c,e);f+=1})}})},zoom:function(e){var b=this.sets.eq(e),h=0,a=this.sets.eq(this.current).children(),d=this;this.busy=!0;this.sets.eq(this.current).children().animate(jQuery.support.opacity?
{transform:"scale(0)",opacity:0}:{opacity:0},{complete:function(){h+=1;if(!(h!=-1&&h<a.length-1)){h=-1;var f=b.children().css(jQuery.support.opacity?{transform:"scale(0)",opacity:0}:{opacity:0}),c=0;d.sets.eq(d.current).hide();b.css("margin-left","").show();f.each(function(a){f.eq(a).css({left:f.eq(a).data("left")}).show();(function(a,b){setTimeout(function(){f.eq(a).show().animate(jQuery.support.opacity?{transform:"scale(1)",opacity:1}:{opacity:1},{complete:function(){if(a==f.length-1)d.busy=!1,
d.current=b},duration:d.options.duration,easing:d.options.easing})},Math.round(d.options.duration/3)*c)})(a,e);c+=1})}},easing:"swing",duration:Math.round(d.options.duration/2)})},deck:function(e){if(!jQuery.support.opacity)return this.zoom(e);var b=e>this.current?"left":"right",h=this.sets.eq(e),a=this.sets.eq(this.current).children(),d=this.sets.eq(e).children(),f=a[e>this.current?"first":"last"](),c=d[e>this.current?"last":"first"](),i=this;b=="right"&&a._reverse();b=="right"&&d._reverse();this.busy=
!0;a.each(function(b){var j=g(this);(function(b,j){setTimeout(function(){j.animate({transform:"scale(0)",opacity:0,left:f.data("left")},{complete:function(){j.hide();b==a.length-1&&(i.sets.eq(i.current).hide(),d.css({transform:"scale(0)",opacity:0,left:c.data("left")}),h.css("margin-left","").show(),d.each(function(b){var c=g(this);(function(b,c){setTimeout(function(){c.animate({transform:"scale(1)",opacity:1,left:c.data("left")},{complete:function(){if(b==d.length-1)a.show().each(function(b){a.eq(b).css({transform:"scale(1)",
opacity:1,left:a.eq(b).data("left")})}),i.busy=!1,i.current=e},duration:i.options.duration,easing:i.options.easing})},Math.round(i.options.duration/3)*b)})(b,c)}))},duration:i.options.duration,easing:i.options.easing})},Math.round(i.options.duration/3)*b)})(b,j)})},drops:function(e){if(!jQuery.support.opacity)return this.zoom(e);var b=e>this.current?"left":"right",h=this.sets.eq(e),a=this.sets.eq(this.current).children().css(o({transition:""})).css(o({transform:"rotate(0deg)",top:0,opacity:1})),d=
this.sets.eq(e).children().css(o({transition:""}));a[e>this.current?"first":"last"]();d[e>this.current?"last":"first"]();var f=this;b=="right"&&a._reverse();b=="right"&&d._reverse();this.busy=!0;a.each(function(b){var i=g(this);(function(b,c){setTimeout(function(){if(q){c.css(o({transition:"all "+f.options.duration+"ms ease-out"}));if(b==a.length-1)c.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){f.sets.eq(f.current).hide();d.css(o({top:f.gheight,opacity:0,transform:"rotate(15deg)"}));
h.css("margin-left","").show();d.each(function(a){var b=g(this);(function(a,b){setTimeout(function(){b.css(o({transition:"all "+f.options.duration+"ms ease-in"}));if(a==d.length-1)b.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){f.busy=!1;f.current=e});b.css(o({opacity:1,top:0,transform:"rotate(0deg)"}))},Math.round(f.options.duration/3)*a)})(a,b)})});c.css(o({opacity:0,top:f.gheight,transform:"rotate(15deg)"}))}else c.animate({opacity:0,top:f.gheight},{complete:function(){c.hide();
b==a.length-1&&(f.sets.eq(f.current).hide(),d.css({top:f.gheight,opacity:0}),h.css("margin-left","").show(),d.each(function(b){var c=g(this);(function(b,c){setTimeout(function(){c.animate({opacity:1,top:0},{complete:function(){if(b==d.length-1)a.show().each(function(b){a.eq(b).css({opacity:1,top:0})}),f.busy=!1,f.current=e},duration:f.options.duration,easing:f.options.easing})},Math.round(f.options.duration/3)*b)})(b,c)}))},duration:f.options.duration,easing:f.options.easing})},20+Math.round(f.options.duration/
3)*b)})(b,i)})}});if(!g.fn._reverse)g.fn._reverse=[].reverse;g.fn[j.prototype.name]=function(){var e=arguments,b=e[0]?e[0]:null;return this.each(function(){var h=g(this);if(j.prototype[b]&&h.data(j.prototype.name)&&b!="initialize")h.data(j.prototype.name)[b].apply(h.data(j.prototype.name),Array.prototype.slice.call(e,1));else if(!b||g.isPlainObject(b)){var a=new j;a.element=h;x.push(a);j.prototype.initialize&&a.initialize.apply(a,e);h.data(j.prototype.name,a)}else g.error("Method "+b+" does not exist on jQuery."+
j.prototype.name)})}})(jQuery);
(function(g){function o(b){for(var b=b.split(")"),e=g.trim,a=b.length-1,d,f,c,i=1,j=0,l=0,o=1,p,t,m,n=0,v=0;a--;){d=b[a].split("(");f=e(d[0]);c=d[1];p=d=t=m=0;switch(f){case "translateX":n+=parseInt(c,10);continue;case "translateY":v+=parseInt(c,10);continue;case "translate":c=c.split(",");n+=parseInt(c[0],10);v+=parseInt(c[1]||0,10);continue;case "rotate":c=q(c);p=Math.cos(c);d=Math.sin(c);t=-Math.sin(c);m=Math.cos(c);break;case "scaleX":p=c;m=1;break;case "scaleY":p=1;m=c;break;case "scale":c=c.split(",");
p=c[0];m=c.length>1?c[1]:c[0];break;case "skewX":p=m=1;t=Math.tan(q(c));break;case "skewY":p=m=1;d=Math.tan(q(c));break;case "skew":p=m=1;c=c.split(",");t=Math.tan(q(c[0]));d=Math.tan(q(c[1]||0));break;case "matrix":c=c.split(","),p=+c[0],d=+c[1],t=+c[2],m=+c[3],n+=parseInt(c[4],10),v+=parseInt(c[5],10)}f=i*p+j*t;j=i*d+j*m;p=l*p+o*t;o=l*d+o*m;i=f;l=p}return[i,j,l,o,n,v]}function w(b){var e,a,d,f=b[0],c=b[1],i=b[2],g=b[3];f*g-c*i?(e=Math.sqrt(f*f+c*c),f/=e,c/=e,d=f*i+c*g,i-=f*d,g-=c*d,a=Math.sqrt(i*
i+g*g),i/=a,g/=a,d/=a,f*g<c*i&&(f=-f,c=-c,d=-d,e=-e)):rotate=e=a=d=0;return{translate:[+b[4],+b[5]],rotate:Math.atan2(c,f),scale:[e,a],skew:[d,0]}}function q(b){return~b.indexOf("deg")?parseInt(b,10)*(Math.PI*2/360):~b.indexOf("grad")?parseInt(b,10)*(Math.PI/200):parseFloat(b)}for(var n=document.createElement("div"),n=n.style,s=["OTransform","msTransform","WebkitTransform","MozTransform","transform"],r=s.length,l,x,j,z,e=/Matrix([^)]*)/;r--;)s[r]in n&&(g.support.transform=l=s[r]);if(!l)g.support.matrixFilter=
x=n.filter==="";n=n=null;g.cssNumber.transform=!0;l&&l!="transform"?(g.cssProps.transform=l,l=="MozTransform"?j={get:function(b,e){return e?g.css(b,l).split("px").join(""):b.style[l]},set:function(b,e){b.style[l]=/matrix[^)p]*\)/.test(e)?e.replace(/matrix((?:[^,]*,){4})([^,]*),([^)]*)/,"matrix$1$2px,$3px"):e}}:/^1\.[0-5](?:\.|$)/.test(g.fn.jquery)&&(j={get:function(b,e){return e?g.css(b,l.replace(/^ms/,"Ms")):b.style[l]}})):x&&(j={get:function(b,h){var a=h&&b.currentStyle?b.currentStyle:b.style,d;
a&&e.test(a.filter)?(d=RegExp.$1.split(","),d=[d[0].split("=")[1],d[2].split("=")[1],d[1].split("=")[1],d[3].split("=")[1]]):d=[1,0,0,1];d[4]=a?a.left:0;d[5]=a?a.top:0;return"matrix("+d+")"},set:function(b,h,a){var d=b.style,f,c,i;if(!a)d.zoom=1;h=o(h);if(!a||a.M)if(c=["Matrix(M11="+h[0],"M12="+h[2],"M21="+h[1],"M22="+h[3],"SizingMethod='auto expand'"].join(),i=(f=b.currentStyle)&&f.filter||d.filter||"",d.filter=e.test(i)?i.replace(e,c):i+" progid:DXImageTransform.Microsoft."+c+")",centerOrigin=g.transform.centerOrigin)d[centerOrigin==
"margin"?"marginLeft":"left"]=-(b.offsetWidth/2)+b.clientWidth/2+"px",d[centerOrigin=="margin"?"marginTop":"top"]=-(b.offsetHeight/2)+b.clientHeight/2+"px";if(!a||a.T)d.left=h[4]+"px",d.top=h[5]+"px"}});j&&(g.cssHooks.transform=j);z=j&&j.get||g.css;g.fx.step.transform=function(b){var e=b.elem,a=b.start,d=b.end,f,c=b.pos,i,n,r,s,p=!1,t=!1,m;i=n=r=s="";if(!a||typeof a==="string"){a||(a=z(e,l));if(x)e.style.zoom=1;f=d.split(a);if(f.length==2)d=f.join(""),b.origin=a,a="none";a=="none"?a={translate:[0,
0],rotate:0,scale:[1,1],skew:[0,0]}:(a=/\(([^,]*),([^,]*),([^,]*),([^,]*),([^,p]*)(?:px)?,([^)p]*)(?:px)?/.exec(a),a=w([a[1],a[2],a[3],a[4],a[5],a[6]]));b.start=a;if(~d.indexOf("matrix"))d=w(o(d));else{d=d.split(")");f=[0,0];for(var A=0,v=[1,1],y=[0,0],B=d.length-1,C=g.trim,k,u;B--;)k=d[B].split("("),u=C(k[0]),k=k[1],u=="translateX"?f[0]+=parseInt(k,10):u=="translateY"?f[1]+=parseInt(k,10):u=="translate"?(k=k.split(","),f[0]+=parseInt(k[0],10),f[1]+=parseInt(k[1]||0,10)):u=="rotate"?A+=q(k):u=="scaleX"?
v[0]*=k:u=="scaleY"?v[1]*=k:u=="scale"?(k=k.split(","),v[0]*=k[0],v[1]*=k.length>1?k[1]:k[0]):u=="skewX"?y[0]+=q(k):u=="skewY"?y[1]+=q(k):u=="skew"&&(k=k.split(","),y[0]+=q(k[0]),y[1]+=q(k[1]||"0"));d={translate:f,rotate:A,scale:v,skew:y}}b.end=d;for(m in a)(m=="rotate"?a[m]==d[m]:a[m][0]==d[m][0]&&a[m][1]==d[m][1])&&delete a[m]}a.translate&&(i=" translate("+(a.translate[0]+(d.translate[0]-a.translate[0])*c+0.5|0)+"px,"+(a.translate[1]+(d.translate[1]-a.translate[1])*c+0.5|0)+"px)",p=!0);a.rotate!=
void 0&&(n=" rotate("+(a.rotate+(d.rotate-a.rotate)*c)+"rad)",t=!0);a.scale&&(r=" scale("+(a.scale[0]+(d.scale[0]-a.scale[0])*c)+","+(a.scale[1]+(d.scale[1]-a.scale[1])*c)+")",t=!0);a.skew&&(s=" skew("+(a.skew[0]+(d.skew[0]-a.skew[0])*c)+"rad,"+(a.skew[1]+(d.skew[1]-a.skew[1])*c)+"rad)",t=!0);b=b.origin?b.origin+i+s+r+n:i+n+r+s;j&&j.set?j.set(e,b,{M:t,T:p}):e.style[l]=b};g.transform={centerOrigin:"margin"}})(jQuery);
