/*
 Copyright (c) 2010 Brandon Aaron (http://brandonaaron.net)
 Licensed under the MIT License (LICENSE.txt).

 Thanks to: http://adomas.org/javascript-mouse-wheel/ for some pointers.
 Thanks to: Mathias Bank(http://www.mathias-bank.de) for a scope bug fix.
 Thanks to: Seamus Leahy for adding deltaX and deltaY

 Version: 3.0.4

 Requires: 1.2.2+
*/
(function(f,e){var a={};e.$widgetkit={lazyloaders:{},load:function(b){a[b]||(a[b]=f.getScript(b));return a[b]},lazyload:function(a){f("[data-widgetkit]",a||document).each(function(){var a=f(this),b=a.data("widgetkit"),e=a.data("options")||{};!a.data("wk-loaded")&&$widgetkit.lazyloaders[b]&&($widgetkit.lazyloaders[b](a,e),a.data("wk-loaded",true))})}};f(function(){$widgetkit.lazyload()})})(jQuery,window);
(function(f){f.browser.msie&&parseInt(f.browser.version)<9&&(f(document).ready(function(){f("body").addClass("wk-ie wk-ie"+parseInt(f.browser.version))}),f.each("abbr,article,aside,audio,canvas,details,figcaption,figure,footer,header,hgroup,mark,meter,nav,output,progress,section,summary,time,video".split(","),function(){document.createElement(this)}))})(jQuery);
(function(f,e){e.$widgetkit.trans={__data:{},addDic:function(a){f.extend(this.__data,a)},add:function(a,b){this.__data[a]=b},get:function(a){if(!this.__data[a])return a;var b=arguments.length==1?[]:Array.prototype.slice.call(arguments,1);return this.printf(String(this.__data[a]),b)},printf:function(a,b){if(!b)return a;var c="",d=a.split("%s");if(d.length==1)return a;for(var e=0;e<b.length;e++)d[e].lastIndexOf("%")==d[e].length-1&&e!=b.length-1&&(d[e]+="s"+d.splice(e+1,1)[0]),c+=d[e]+b[e];return c+
d[d.length-1]}}})(jQuery,window);
(function(f){f.easing.jswing=f.easing.swing;f.extend(f.easing,{def:"easeOutQuad",swing:function(e,a,b,c,d){return f.easing[f.easing.def](e,a,b,c,d)},easeInQuad:function(e,a,b,c,d){return c*(a/=d)*a+b},easeOutQuad:function(e,a,b,c,d){return-c*(a/=d)*(a-2)+b},easeInOutQuad:function(e,a,b,c,d){return(a/=d/2)<1?c/2*a*a+b:-c/2*(--a*(a-2)-1)+b},easeInCubic:function(e,a,b,c,d){return c*(a/=d)*a*a+b},easeOutCubic:function(e,a,b,c,d){return c*((a=a/d-1)*a*a+1)+b},easeInOutCubic:function(e,a,b,c,d){return(a/=
d/2)<1?c/2*a*a*a+b:c/2*((a-=2)*a*a+2)+b},easeInQuart:function(e,a,b,c,d){return c*(a/=d)*a*a*a+b},easeOutQuart:function(e,a,b,c,d){return-c*((a=a/d-1)*a*a*a-1)+b},easeInOutQuart:function(e,a,b,c,d){return(a/=d/2)<1?c/2*a*a*a*a+b:-c/2*((a-=2)*a*a*a-2)+b},easeInQuint:function(e,a,b,c,d){return c*(a/=d)*a*a*a*a+b},easeOutQuint:function(e,a,b,c,d){return c*((a=a/d-1)*a*a*a*a+1)+b},easeInOutQuint:function(e,a,b,c,d){return(a/=d/2)<1?c/2*a*a*a*a*a+b:c/2*((a-=2)*a*a*a*a+2)+b},easeInSine:function(e,a,b,c,
d){return-c*Math.cos(a/d*(Math.PI/2))+c+b},easeOutSine:function(e,a,b,c,d){return c*Math.sin(a/d*(Math.PI/2))+b},easeInOutSine:function(e,a,b,c,d){return-c/2*(Math.cos(Math.PI*a/d)-1)+b},easeInExpo:function(e,a,b,c,d){return a==0?b:c*Math.pow(2,10*(a/d-1))+b},easeOutExpo:function(e,a,b,c,d){return a==d?b+c:c*(-Math.pow(2,-10*a/d)+1)+b},easeInOutExpo:function(e,a,b,c,d){return a==0?b:a==d?b+c:(a/=d/2)<1?c/2*Math.pow(2,10*(a-1))+b:c/2*(-Math.pow(2,-10*--a)+2)+b},easeInCirc:function(e,a,b,c,d){return-c*
(Math.sqrt(1-(a/=d)*a)-1)+b},easeOutCirc:function(e,a,b,c,d){return c*Math.sqrt(1-(a=a/d-1)*a)+b},easeInOutCirc:function(e,a,b,c,d){return(a/=d/2)<1?-c/2*(Math.sqrt(1-a*a)-1)+b:c/2*(Math.sqrt(1-(a-=2)*a)+1)+b},easeInElastic:function(e,a,b,c,d){var e=1.70158,g=0,f=c;if(a==0)return b;if((a/=d)==1)return b+c;g||(g=d*0.3);f<Math.abs(c)?(f=c,e=g/4):e=g/(2*Math.PI)*Math.asin(c/f);return-(f*Math.pow(2,10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/g))+b},easeOutElastic:function(e,a,b,c,d){var e=1.70158,g=0,f=c;if(a==
0)return b;if((a/=d)==1)return b+c;g||(g=d*0.3);f<Math.abs(c)?(f=c,e=g/4):e=g/(2*Math.PI)*Math.asin(c/f);return f*Math.pow(2,-10*a)*Math.sin((a*d-e)*2*Math.PI/g)+c+b},easeInOutElastic:function(e,a,b,c,d){var e=1.70158,g=0,f=c;if(a==0)return b;if((a/=d/2)==2)return b+c;g||(g=d*0.3*1.5);f<Math.abs(c)?(f=c,e=g/4):e=g/(2*Math.PI)*Math.asin(c/f);return a<1?-0.5*f*Math.pow(2,10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/g)+b:f*Math.pow(2,-10*(a-=1))*Math.sin((a*d-e)*2*Math.PI/g)*0.5+c+b},easeInBack:function(e,
a,b,c,d,f){f==void 0&&(f=1.70158);return c*(a/=d)*a*((f+1)*a-f)+b},easeOutBack:function(e,a,b,c,d,f){f==void 0&&(f=1.70158);return c*((a=a/d-1)*a*((f+1)*a+f)+1)+b},easeInOutBack:function(e,a,b,c,d,f){f==void 0&&(f=1.70158);return(a/=d/2)<1?c/2*a*a*(((f*=1.525)+1)*a-f)+b:c/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+b},easeInBounce:function(e,a,b,c,d){return c-f.easing.easeOutBounce(e,d-a,0,c,d)+b},easeOutBounce:function(e,a,b,c,d){return(a/=d)<1/2.75?c*7.5625*a*a+b:a<2/2.75?c*(7.5625*(a-=1.5/2.75)*a+0.75)+
b:a<2.5/2.75?c*(7.5625*(a-=2.25/2.75)*a+0.9375)+b:c*(7.5625*(a-=2.625/2.75)*a+0.984375)+b},easeInOutBounce:function(e,a,b,c,d){return a<d/2?f.easing.easeInBounce(e,a*2,0,c,d)*0.5+b:f.easing.easeOutBounce(e,a*2-d,0,c,d)*0.5+c*0.5+b}})})(jQuery);
(function(f){function e(a){var c=a||window.event,d=[].slice.call(arguments,1),e=0,i=0,h=0,a=f.event.fix(c);a.type="mousewheel";a.wheelDelta&&(e=a.wheelDelta/120);a.detail&&(e=-a.detail/3);h=e;c.axis!==void 0&&c.axis===c.HORIZONTAL_AXIS&&(h=0,i=-1*e);c.wheelDeltaY!==void 0&&(h=c.wheelDeltaY/120);c.wheelDeltaX!==void 0&&(i=-1*c.wheelDeltaX/120);d.unshift(a,e,i,h);return f.event.handle.apply(this,d)}var a=["DOMMouseScroll","mousewheel"];f.event.special.mousewheel={setup:function(){if(this.addEventListener)for(var b=
a.length;b;)this.addEventListener(a[--b],e,false);else this.onmousewheel=e},teardown:function(){if(this.removeEventListener)for(var b=a.length;b;)this.removeEventListener(a[--b],e,false);else this.onmousewheel=null}};f.fn.extend({mousewheel:function(a){return a?this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
